name = "hfttb"
uuid = "7ed62fd1-ac14-4325-a0ad-ae9aa32ec12e"
authors = ["linan <linanisyugioh@163.com>"]
version = "1.0.0-DEV"

[deps]
CBinding = "d43a6710-96b8-4a2d-833c-c424785e5374"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
FinancialStruct = "d8e75018-0be8-473d-856a-83ea1b53af75"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
